# Generated by Django 5.2.9 on 2025-12-05 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TravelUsersProfile',
            new_name='TravelUserProfile',
        ),
    ]
